Add finished exercise 11.18

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -44,20 +44,30 @@ jobs:
         run: npm run test:e2e
 
       - name: Trigger deployment
+        if: ${{ env.DEPLOY_FLAG == 'true' }}
         run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
 
-      - name: Health Check
-        run: |
-          echo "Waiting for server to start..."
-          sleep 30
-          echo "Checking health of deployed app..."
-          response=$(curl --fail https://full-stack-open-pokedex-jvcn.onrender.com/healthz)
-          if [ "$response" == "ok" ]; then
-            echo "Health check passed!"
-          else
-            echo "Health check failed!"
-            exit 1
-          fi
+      - name: Notify success
+        uses: stegzilla/discord-notify@v4
+        if: ${{ env.DEPLOY_FLAG == 'true' && success() }}
+        with:
+          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
+          title: A new version of Pokedex deployed!
+          message: '**${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}**'
+          include_image: true
+          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
+          username: GitHub PR Notifier
+
+      - name: Notify failure
+        uses: stegzilla/discord-notify@v4
+        if: failure()
+        with:
+          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
+          title: Deployment failed!
+          message: '**${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}**'
+          include_image: true
+          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
+          username: GitHub PR Notifier
 
   tag_release:
     if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), 'skip') }}
@@ -75,3 +85,16 @@ jobs:
           WITH_V: true
           DEFAULT_BUMP: patch
           RELEASE_BRANCHES: main
+
+      - name: Health Check
+        run: |
+          echo "Waiting for server to start..."
+          sleep 30
+          echo "Checking health of deployed app..."
+          response=$(curl --fail https://full-stack-open-pokedex-jvcn.onrender.com/healthz)
+          if [ "$response" == "ok" ]; then
+            echo "Health check passed!"
+          else
+            echo "Health check failed!"
+            exit 1
+          fi
